# Generated by Django 4.1 on 2022-08-20 16:12

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-modified_at',)},
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='product.image', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.CharField(choices=[('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('Default', 'Default')], max_length=20, null=True),
        ),
    ]
